[package]
name = "rust-wasm-interpreter"
version = "0.1.0"
authors = ["Jeffrey Smith II <jeffreyssmith2nd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasabi_leb128 = "0.4.0"